### ISSUE TITLE
sentence-level or token-level transformation

### ISSUE THREAD

**Issue by YWMditto** [hanqi-qi/tokenUni#2]
Hello! Congratulations for your great work!

I am confused about the use of soft decay in the 'Unsupervised Evaluation on STS datasets'. It seems that you use the `soft_expand` function on the output sentence embedings of the whole sts dataset, instead of using the function on each sample's output token embeddings.

Isn't that quite different from your paper？

Thanks for your reply!

**Comment by hanqi-qi** [comment]
> Hello! Congratulations for your great work!
> 
> I am confused about the use of soft decay in the 'Unsupervised Evaluation on STS datasets'. It seems that you use the `soft_expand` function on the output sentence embedings of the whole sts dataset, instead of using the function on each sample's output token embeddings.
> 
> Isn't that quite different from your paper？
> 
> Thanks for your reply!

Hi! The transformation is applied to the sentence-level output, [sentence_len, hidden_size]. It is the same as the paper description.  In algorithm 1, the input X is n_l \times m.  In fact, in our paper token uniformity refers to the representations that are similar, but not limited to the token representation. Sorry for the confusion.

**Comment by YWMditto** [comment]
First thanks for your reply!
And I want to ask:
1. Does the sentence level transformation share the same theoratical analysis as the token level?
2. How should I know when it is more suitable to use sentence level transformation and when token level is better? 
3. When using sentence level transformation, is the sentence number bigger better?

Best wishes!

**Comment by hanqi-qi** [comment]
> First thanks for your reply! And I want to ask:
> 
> 1. Does the sentence level transformation share the same theoratical analysis as the token level?
> 2. How should I know when it is more suitable to use sentence level transformation and when token level is better?
> 3. When using sentence level transformation, is the sentence number bigger better?
> 
> Best wishes!

Yes, you can apply the analysis to different representations. We did not experiment with the settings you mentioned, but it could be interesting to see the performances in different situations.  Looking forward to your new findings!

**Comment by YWMditto** [comment]
Thanks for your answer, I will shut down this issue.

Best wishes!
